name: Deploy Bot to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy code to server
        run: |
          ssh root@${{ secrets.VPS_IP }} "cd /root/todo-notify-tg-bot && git pull origin main"

      - name: Restart bot service
        run: |
          ssh root@${{ secrets.VPS_IP }} "systemctl restart todo-bot"
